### ISSUE TITLE
Apivore is not being released to RubyGems in a while

### ISSUE THREAD

**Issue by lucasrenan** [westfieldlabs/apivore#101]
Hey @ashoda @gwshaw @jreece1567 

I was checking https://rubygems.org/gems/apivore then I realized apivore is not being released to RubyGems since February 2016.

What's blocking the new releases?

Thanks!

**Comment by gwshaw** [comment]
The dev here that managed this repo left several months ago and no one pickedit up. We're working on that now.

**Comment by ashoda** [comment]
@lucasrenan the latest version has been released albeit with an outdated date.

**Comment by lucasrenan** [comment]
@gwshaw @ashoda 👍
