### ISSUE TITLE
Providing query and path parameters?

### ISSUE THREAD

**Issue by MiralDesai** [westfieldlabs/apivore#119]
The readme say to provide dummy data for a parameter in the path, you can use the following create a params variable and attach it to the end of the method like so:

`:get, '/url/{id}/moreurl', 200, params`

It also says you can provide query parameters like this: 

`:get, '/url/{id}/moreurl', 200,{"_query_string" => "title=Hello%20World&edition=3"}`

but what about both together? There are no docs for that and I keep getting an error saying wrong number of arguments, given 5, expected 3..4.

Surely there's support for it and I'm just blind? Hoping so anyway.

**Comment by thomasrossetto** [comment]
Hi @MiralDesai , you can add id in params hash in this way:

`:get, '/url/{id}/moreurl', 200,{"_query_string" => "title=Hello%20World&edition=3" , "id" => 10}`
