### ISSUE TITLE
Apivore hides parsing errors

### ISSUE THREAD

**Issue by gwagener** [westfieldlabs/apivore#23]
If there is a parsing error in the Swagger docs file, YAML in my case, Apivore hides this error by failing with `'each_response': undefined method 'each' for nil:NilClass (NoMethodError)` at https://github.com/westfieldlabs/apivore/blob/master/lib/apivore.rb#L26.

The error is present in `session.response.body` at https://github.com/westfieldlabs/apivore/blob/master/lib/apivore/rspec_builder.rb#L51, but gets lost when creating the Mash.

Apivore should report failures instead of just dying itself. Probably bubbling the parsing error would be fine. This would provide the line numbers of the parsing error.

**Comment by hornc** [comment]
I _think_, if I understand this correctly, this specific issue has been fixed a while ago by PR https://github.com/westfieldlabs/apivore/pull/12/files

specifically: https://github.com/westfieldlabs/apivore/pull/12/files#diff-0e1c023af79d80cee777771d3e2384afR41

If the server doesn't respond neatly, which I think is what is happening when there is a YAML parsing problem, it'll raise a hopefully more informative exception now.

I'm going to look around this area further to check that it does the right thing when the server responds with 500s and other malformed json, but I think this issue can be closed.

**Comment by gwagener** [comment]
I tested with the latest version of Apivore. I think I replicated the parsing error and did get back a useful error so I think this is fixed.
