### ISSUE TITLE
Incorrect error message for substitute data error

### ISSUE THREAD

**Issue by gwshaw** [westfieldlabs/apivore#33]
If the .yml file has this:
paths:
  '/centres/{centre_id}/movies.{format}':

and the swagger spec has this:

  apivore_setup '/centres/{centre_id}/movies.json', 'get', '200' do
    { 'centre_id' => @centre_id}
  end

(note".json" rather than {format} parameter.

The error generated is:

2) the API path /centres/{centre_id}/movies/{movie_id}.{format} method get response 200 responds with the specified models
     Failure/Error: path.scan(/\{([^\}]*)\}/).each do |param|
     URI::InvalidURIError:
       No substitution data found for {centre_id} to test the path /centres/{centre_id}/movies/{movie_id}.{format}.
       Add it via an:
         apivore_setup '<path>', '<method>', '<response>' do
           { 'centre_id' => <value> }
         end
       block in your specs.
     # /Users/george/.rvm/gems/ruby-2.2.0/bundler/gems/apivore-896dcb54528e/lib/apivore/rspec_builder.rb:30:in `each'
     # /Users/george/.rvm/gems/ruby-2.2.0/bundler/gems/apivore-896dcb54528e/lib/apivore/rspec_builder.rb:30:in `apivore_build_path'
     # /Users/george/.rvm/gems/ruby-2.2.0/bundler/gems/apivore-896dcb54528e/lib/apivore/rspec_builder.rb:77:in `block (3 levels) in validate'

Either the path should not match, it should complain about the correct substitution parameter, or be silent and just use the '.json' from the supplied path.

**Comment by hornc** [comment]
With Apivore v1.0 the error message is now:

`Swagger doc: /swagger.json does not have a documented path for /centres/{centre_id}/movies.json`

which is correct.
