### ISSUE TITLE
Json_Schema gem needs higher minimum version

### ISSUE THREAD

**Issue by gwshaw** [westfieldlabs/apivore#81]
The requirement of jason_schema gem 2.5 passes the Gem's test, but in-use fails unless jason_schema 2.6 or greater is used. Bundler is not, for unknown reasons, using the latest version (2.6.1) and the bundled version (2.5) fails with webmock issues. Removing Apivore from the gem file shows no other dependencies on the jason_schema gem.

**Comment by ashoda** [comment]
Closing for the time being. We can re-raise if need be.
