### ISSUE TITLE
Allow use of full URL for consistency check

### ISSUE THREAD

**Issue by gwshaw** [westfieldlabs/apivore#82]
Apivore assumes that the master document swagger is at a fixed address of `http://<host>/swagger.json`. This is limiting in that the protocol, path, and any authentication cannot be specified. Simply using the full URL addresses some of these issues, thus:
```Ruby
    it 'has definitions consistent with the master docs' do
      expect(subject).to be_consistent_with_swagger_definitions(
        'https://api.westfield.io/swagger/1.json', 'deal'
      )
```
Looking for `http` allows the current behaviour as well as fully specified URL.

**Comment by hornc** [comment]
Resolved by https://github.com/westfieldlabs/apivore/pull/83
