### ISSUE TITLE
validate_all_paths - Untested for response code default

### ISSUE THREAD

**Issue by mjarosinski** [westfieldlabs/apivore#85]
Are 'default' status codes supported? Getting 'untested for response code for default' even after setting up the following:

`expect(subject).to validate(
                    :post, "/discussion_comment/update", "default", {
                        "_data" => {
                        }
                    }
                )
`

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object-example

**Comment by ashoda** [comment]
closing in favor of https://github.com/westfieldlabs/apivore/issues/86
