### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by amcaplan** [westfieldlabs/apivore#97]
`CONTRIBUTING.MD` says:

> We aim to respond to pull requests within a few business days, and, typically, within one business day.

Looking at issues and open PRs, it seems like it's been about a year since any activity happened on this project, despite a good number of Issues and PRs that have happened since then.  I recently found a small issue and considered submitting a PR, but it doesn't look like there's much point in the current situation.

I'm the last person to play the blame game and demand anything from open source maintainers, so don't expect that.  But this gem has >100,000 downloads on RubyGems, and there's a reason for it.  It's really useful to a lot of people, and whether or not Westfield Labs has time for it, someone should be maintaining it actively.  It would be a shame to let it die with Rails 5 and the compatibility issues that has introduced.

Perhaps the original maintainers would be interested in passing on the responsibility to others?

**Comment by ashoda** [comment]
@amcaplan thanks for reaching out. There hasn't been a primary owner for this gem in the org as of late, but we do intend to continue maintaining apivore. We will be responding to the outstanding issues and PRs over the next week.

cc: @jreece1567
